### ISSUE TITLE
component的Model隔离，使用通知机制还是标识机制

### ISSUE THREAD

**Issue by leowang721** [fcfe/fc-component-ria#13]
@fcfe/fc-component-ria  各位
是否有必要进一步隔离Model。
行为为：
1. 每个component自己有自己的Model，行为不变
2. sharedModel的更新不再是默认直接去进行它的更新，而是在修改自己的数据时使用类似于
```javascript
this.model.set('sth', 'sthelse', { updateShared: true };
```
类似于这种语法的东西，来标识我要更新sharedModel，也就是全局数据，进而去影响其他的Component。数据驱动的方式。

请直接回复讨论。

**Comment by leowang721** [comment]
@fcfe/fc-component-ria 请各位参与讨论

**Comment by leowang721** [comment]
通知机制：当前的形式，可以通过autoSyncModel和syncSharedModel控制
标识机制：就是上面说的
```javascript
this.model.set('sth', 'sthelse', { updateShared: true }
```

**Comment by leowang721** [comment]
#6

**Comment by zhangshaolong** [comment]
我是说我的想法
借鉴的是angularjs的scope
每个顶层的应用有一个rootScope，这个里面存放的是Model数据
在应用里面的component，都有对应的subScope，他会共享父级的scope的Model数据，但不可以修改，只是读共享
如果父scope中有一个a，子里面也有一个a，那么子里面操作的只是自己的a，不会干扰父scope
这样的结构，是可多层嵌套的
然后再为scope对象添加事件通知机制
可以把由rootScope创建的多层scope是一家子，他们之间可以互相打招呼，这个功能使用的是事件通知
目前我已经实现了这样的一个简单的模型

**Comment by leowang721** [comment]
@zhangshaolong 当前的实现，就是默认共享数据，并且自己的Model修改时其实是不会影响sharedModel的。
but，我们的sharedModel是页面级别的，当前取消了父子层级的概念。
通过sharedModel的数据改变来进行驱动其他视图的改变，势必要有一种通知的机制。
我想的是，既然修改sharedModel的数据是`有风险的`，那么通过显示的标记来进行处理，至少意味着我已经认识到这个风险了。

**Comment by leowang721** [comment]
是否还有更好的机制？

**Comment by leowang721** [comment]
@zhangshaolong 你需要更透彻一些说明你预想的交互机制，即使用事件通知方式如何处理页面？

**Comment by leowang721** [comment]
当前使用标识
